### ISSUE TITLE
node.js send email

### ISSUE THREAD

**Issue by panhead63** [mskel1/unaAdventures#32]
https://github.com/barrycumbie/crispy-sniffle-romeo/issues/7

**Comment by kwilliams31** [comment]
https://github.com/barrycumbie/crispy-sniffle-romeo/issues/15
user input their number to send

**Comment by kwilliams31** [comment]
Have to different providers where they can click, enter their number and whatever secrets they want

**Comment by barrycumbie** [comment]
Okay...I can help with this. 

Point me a bit more precisely to code...permalink?

What file/what line for the button they click? Any variables to pull from, like their name or stuff from db?

My crispy sniffle has that...they enter their phone number and select att or Verizon. (Maybe version didn't work yet?)

**Comment by kwilliams31** [comment]
I looked at your code you updated and I got it to work on ours! I think I have everything in correctly. Verizon works good, I checked it with my number idk about AT&T though

> Okay...I can help with this.
> 
> Point me a bit more precisely to code...permalink?
> 
> What file/what line for the button they click? Any variables to pull from, like their name or stuff from db?
> 
> My crispy sniffle has that...they enter their phone number and select att or Verizon. (Maybe version didn't work yet?)
